### ISSUE TITLE
Kata-Log und Warm-Ups in Lernpfad übernehmen

### ISSUE THREAD

**Issue by simondueckert** [cogneon/lernos-sketchnoting#11]
Das Kapitel „Der Sketchnote Lernpfad“ sollte alle Übungen enthalten, dafür das aktuelle Kapitel 6 und 7 als Unterkapitel in 5 überführen (macht dann auch das Inhaltsverzeichnis kompakter).

Kata-Log: „Log“ verwenden wir bisher als Begriff nicht, könnt ihr das in „Sketchnoting Katas“ umbenennen?

Warm-ups: die Überschriften 7.x sind im Inhaltsverzeichnis fett. Sind die evtl. manuell neben Heading 2 auch auf **bold** gesetzt? Wenn ja, bold entfernen.

**Comment by ben1kk** [comment]
Ja, es waren einige überschriften auch auf bold. Ist jetzt draussen.

**Comment by ben1kk** [comment]
Die Struktur und der "Kata-Log" sollen erhalten bleiben.
