### ISSUE TITLE
Ressourcen in Grundlagen-Kapitel

### ISSUE THREAD

**Issue by simondueckert** [cogneon/lernos-sketchnoting#12]
Im Barcamp-Leitfaden wollen wir die Ressourcen-Sammlung ans Ende des Grundlagen-Kapitel stellen, damit das eine kompakte Einheit bildet (z.B. beim Import des Grundlagen-Kapitels in Intranets/Wikis).

Wenn nichts dagegen spricht Kapitel 8 als Kapitel 4.5 in die Grundlagen umziehen.

**Comment by ben1kk** [comment]
Die Ressourcen sollen als "Kompendium" am Ende des Dokument stehen bleiben.
