### ISSUE TITLE
Standard-Vorwort einfügen

### ISSUE THREAD

**Issue by simondueckert** [cogneon/lernos-sketchnoting#7]
Die Idee des Vorworts in der High Level Structure ist, dass alle Nutzer aller Guides die Grundidee von lernOS verstehen. Daher soll es in allen Guides gleich sein.

Aktueller Text (wenn ihr den einfügen wollt, stelle ich das Markdown dazu in das lernOS Core Repo):

Das Verb "lernos" ist die Zukunftsform von "lernen" auf Esperanto (mi lernos = ich werde lernen, ni lernos = wir werden lernen). lernOS ist ein Betriebssystem für Lebenslanges Lernen und Lernende Organisationen. lernOS ist aber keine Software, sondern "Brainware". Es ist eine Art zu Denken und zu Handeln, um als Einzelperson, Team oder Organisation im 21. Jahrhundert erfolgreich zu sein. Das groß geschriebene "OS" im Namen unterstreicht die Bedeutung der Digitalisierung für unsere vernetzte Wissensgesellschaft.

Zu lernOS gibt es drei grundlegende Leitfäden beschrieben, die den Ansatz auf individueller Ebene (lernOS für Dich), auf Ebene von Teams (lernOS für Teams) und auf Ebene von Organisationen (lernOS für Organisationen) beschreiben. Zusätzlich gibt es die lernOS Toolbox, die oft genutzte Methoden und Werkzeuge erklären (z.B. Podcast, Barcamp, Sketchnoting, Expert Debriefing). lernOS ist nicht auf der sprichwörtlichen grünen Wiese entstanden, sondern ist eine Zusammenstellung von bereits bestehenden und bewährten Methoden. Alle lernOS Leitfäden sind unter der offenen Lizenz Creative Commons Attribution (CC BY) auf der lernOS Webseite verfügbar und können gerne an die eigenen Bedürfnisse angepasst werden.

Wenn du weitere Fragen bezüglich lernOS hast, oder Unterstützung von Gleichgesinnten brauchst, kannst du die Community-Plattform CONNECT nutzen oder mit #lernOS auf Twitter schreiben. Beachte: Die Meisterschaft von lernOS ist eine Frage von Monaten oder Jahren, nicht Stunden oder Tagen. Also: Keep Calm & Learn On!

Dein @simondueckert

**Comment by ben1kk** [comment]
Vorwort ist eingebaut.
