### ISSUE TITLE
Inhaltsverzeichnis auf zwei Überschriftsebene beschränken

### ISSUE THREAD

**Issue by simondueckert** [cogneon/lernos-sketchnoting#9]
lernOS Guides sollen durchaus „inhaltsschwer“ sein, die Anwender aber nicht erschrecken. Eine Maßnahme dafür ist, das Inhaltsverzeichnis knapp zu halten. Dafür haben wir in der aktuellen Vorlagenversion die Tiefe des Inhaltsverzeichnis auf zwei Ebenen zu beschränken.

Zeile in metadata.yaml dazu:

toc-depth: 2

**Comment by ben1kk** [comment]
Ist eingebaut.
